name: Automatic Deployment

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Welcome
        run: echo Start deploying Project Kylan
      - name: Install Solana CLI
        run: sh -c "$(curl -sSfL https://release.solana.com/stable/install)" && source ~/.profile && source ~/.bash_profile
      - run: cat ~/.profile && cat ~/.bash_profile
      - name: Publish npm package
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm i -g @project-serum/anchor-cli && npm install
      - run: anchor build && npm run build
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Deploy docs to gh-pages branch
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
